config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  namespace :admin do
    resources :members,except:[:new, :create, :destroy]
    resources :genres, except:[:new, :show, :destroy]
    resources :items, except:[:destroy]
    resources :orders, except:[:new, :create, :edit, :destroy]
    resources :ordered_items, only:[:update]
    root 'homes#top'
  end

  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations',
    passwords: 'members/passwords'
  }

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resource :member, except:[:create, :new, :destroy] do
      collection do
        get 'leave'
        put 'actived'
        patch 'actived'
      end
    end

    resources :delivery_destinations, except:[:show, :new]
    resources :items, except:[:destroy]
    resources :cart_items, except:[:show, :new, :edit] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        post 'check'
        get 'thanks'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  validates :quantity, presence: true

end

app/models/delivery_destination.rb
class DeliveryDestination < ApplicationRecord
  belongs_to :member
  
  def full_address
    "#{self.postal_code} #{self.address} #{self.reciever_name}"
  end
  
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orderd_items, dependent: :destroy
  belongs_to :genre

 attachment :item_image
 
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  has_many :delivery_destinations, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :last_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true
  
  def registered?(delivery_destination)
    self.delivery_destinations.where(address: delivery_destination.address, postal_code: delivery_destination.postal_code, reciever_name: delivery_destination.reciever_name).exists? || delivery_destination.postal_code == self.postal_code && delivery_destination.address == self.address
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :ordered_items, dependent: :destroy
  has_many :items, through: :ordered_items
  belongs_to :member

  
  enum order_status: {入金待ち: 0, 入金確認中: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum make_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

  def tax_included_price
    (self.item.tax_excluded_price * 1.1).to_i
  end
  
  def total_amount
    (self.quantity * tax_included_price).to_i
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
    @tax_excluded_price = @item.tax_excluded_price*1.1
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:item_name, :introduction, :item_image, :genre_id, :tax_excluded_price, :sales_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(resource_or_scope)
    if resource_or_scope =- current_member
       stored_location_for(resource_or_scope) || root_path
    elsif resource_or_scope == current_admin
       stored_location_for(resource_or_scope) || admin_root_path
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope == current_member
       stored_location_for(resource_or_scope) || root_path
       items_path
    elsif resource_or_scope == current_admin
       stored_location_for(resource_or_scope) || admin_root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :member
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/delivery_destinations_helper.rb
module DeliveryDestinationsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/items/edit.html.erb
<div class="container">


<h2 class="title">商品編集</h2>

<%= form_with model: @item, url: admin_item_path, local: true do |f| %>

<div class="col-xs-6 display-center">
  <%= f.file_field :item_image %>
</div>

<div class="col-xs-6">
   <div class="form-group display-flex">
     <%= f.label :item_name, '商品名' %>
     <%= f.text_field :item_name %>
    </div>
    <div class="form-group display-flex">
      <%= f.label :introduction, '商品説明' %>
      <%= f.text_area :introduction %>
    </div>
    <div class="form-group display-flex">
      <%= f.label :genre_id, 'ジャンル' %>
      <%= f.collection_select(:genre_id, @genres, :id, :genre_name, prompt: "--選択して下さい") %>
    </div>
    <div class="form-group display-flex">
      <%= f.label :tax_excluded_price, '税抜価格' %>
      <%= f.text_field :tax_excluded_price %>
    </div>

    <div class="form-group display-flex">
      <%= f.label :sales_status,  '販売ステータス', class: "control-label" %>
      <%= f.select :sales_status, [['販売中', 0], ['販売停止中', 1]], prompt: "-- 選択してください --", class: "col-sm-7 form-area" %>
    </div>

</div>
<div class="actions text-right">
    <%= f.submit '変更を保存', class: 'btn btn-primary' %>
    </div>
<% end %>

</div>

app/views/admin/items/index.html.erb
<div class="container">

<h2 class="title">商品一覧</h2>
<%= link_to "+", new_admin_item_path, data: {"turbolinks" => false}, class: "pull-right circle" %>
<div>
<table class="col-xs-9 table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td>
        <%= link_to admin_item_path(item.id) do %>
        <%= item.item_name %>
        <% end %>
      </td>
      <td><%= item.tax_excluded_price.to_s(:delimited) %></td>
      <td><%= item.genre.genre_name %></td>
      <td><% if item.sales_status == 0 %>
	   	     <p>販売中</p>
	   	   <% elsif item.sales_status == 1 %>
	   	     <p>販売停止中</p>
	   	  <% end %>
	   	 </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
<h2 class="title">商品新規登録</h2>
<div>

<%= form_with model: @item, url: admin_items_path, local: true do |f| %>
  <div class="col-xs-6 display-center">
    <%= f.attachment_field :item_image %>
  </div>

  <div class="col-xs-6">
    <div class="form-group display-flex">
     <%= f.label :item_name, '商品名' %>
     <%= f.text_field :item_name %>
    </div>

    <div class="form-group display-flex">
      <%= f.label :introduction, '商品説明' %>
      <%= f.text_area :introduction %>
    </div>

    <div class="form-group display-flex">
      <%= f.label :genre_id, 'ジャンル' %>
      <%= f.collection_select(:genre_id, @genres, :id, :genre_name, prompt: "--選択して下さい") %>
    </div>

    <div class="form-group display-flex">
      <%= f.label :tax_excluded_price, '税抜価格' %>
      <%= f.text_field :tax_excluded_price %>
    </div>

    <div class="form-group display-flex">
      <%= f.label :sales_status,  '販売ステータス', class: "control-label" %>
      <%= f.select :sales_status, [['販売中', 0], ['販売停止中', 1]], prompt: "-- 選択してください --", class: "col-sm-7 form-area" %>
    </div>
    </div>

    <div class="actions text-right btn-right">
    <%= f.submit '新規登録', class: 'btn btn-primary' %>
    </div>
<% end %>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">

<h2 class="title">商品詳細</h2>

<div class="row">
<div class="col-xs-6">
 <%= attachment_image_tag @item, :item_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.png", size: '400x200' %>
</div>
<div class="col-xs-6">
  <div class="form-group display-flex">
    <label>商品名</label>
     <%= @item.item_name %>
  </div>
  <div class="form-group display-flex">
    <label>商品説明</label>
    <%= @item.introduction %>
  </div>
  <div class="form-group display-flex">
    <label>ジャンル</label>
    <%= @item.genre.genre_name %>
  </div>
  <div class="form-group display-flex">
    <label>税込価格(税抜き価格)</label>
    <%= @tax_excluded_price.floor.to_s(:delimited) %>
    (<%= @item.tax_excluded_price.to_s(:delimited) %>)円
  </div>
  <div class="form-group display-flex">
   <p>販売ステータス</p>
 	   <% if @item.sales_status == 0 %>
 	     <p>販売中</p>
 	   <% elsif @item.sales_status == 1 %>
 	     <p>販売停止中</p>
 	  <% end %>
	 </div>
</div>
</div>

<div class="text-right">
  <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-primary" %>
</div>

</div>