config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  namespace :admin do
    resources :members,except:[:new, :create, :destroy]
    resources :genres, except:[:new, :show, :destroy]
    resources :items, except:[:destroy]
    resources :orders, except:[:new, :create, :edit, :destroy]
    resources :ordered_items, only:[:update]
    root 'homes#top'
  end

  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations',
    passwords: 'members/passwords'
  }

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resource :member, except:[:create, :new, :destroy] do
      collection do
        get 'leave'
        put 'actived'
        patch 'actived'
      end
    end

    resources :delivery_destinations, except:[:show, :new]
    resources :items, except:[:destroy]
    resources :cart_items, except:[:show, :new, :edit] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        post 'check'
        get 'thanks'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  validates :quantity, presence: true

end

app/models/delivery_destination.rb
class DeliveryDestination < ApplicationRecord
  belongs_to :member
  
  def full_address
    "#{self.postal_code} #{self.address} #{self.reciever_name}"
  end
  
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orderd_items, dependent: :destroy
  belongs_to :genre

 attachment :item_image
 
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  has_many :delivery_destinations, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :last_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true
  
  def registered?(delivery_destination)
    self.delivery_destinations.where(address: delivery_destination.address, postal_code: delivery_destination.postal_code, reciever_name: delivery_destination.reciever_name).exists? || delivery_destination.postal_code == self.postal_code && delivery_destination.address == self.address
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :ordered_items, dependent: :destroy
  has_many :items, through: :ordered_items
  belongs_to :member

  
  enum order_status: {入金待ち: 0, 入金確認中: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum make_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

  def tax_included_price
    (self.item.tax_excluded_price * 1.1).to_i
  end
  
  def total_amount
    (self.quantity * tax_included_price).to_i
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_up_path_for(resource_or_scope)
    if resource_or_scope =- current_member
       stored_location_for(resource_or_scope) || root_path
    elsif resource_or_scope == current_admin
       stored_location_for(resource_or_scope) || admin_root_path
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope == current_member
       stored_location_for(resource_or_scope) || root_path
       items_path
    elsif resource_or_scope == current_admin
       stored_location_for(resource_or_scope) || admin_root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :member
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/delivery_destinations_helper.rb
module DeliveryDestinationsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer_inner">
  <div class="footer_box">© ずんだ餅Family</div>
</div>

app/views/layouts/_header.html.erb
  <h2 class="nav nav-pills navbar-left logo">
    <% if admin_signed_in? %>
    <%= link_to "NaGaNo-cake", admin_root_path, class: "logo_txt" %>
    <% else %>
    <%= link_to "NaGaNo-cake", root_path, class: "logo_txt" %>
    <% end %>
  </h2>

  <nav>
    <ul class="nav nav-pills navbar-right">
      <% if member_signed_in? %>
       <!--メンバーログイン-->
        <li class="header-name">
          ようこそ、<%= current_member.first_name %><%= current_member.last_name %>さん！
        </li>
        <li class="header_item">
          <%= link_to " my page", member_path(current_member), class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " items", items_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " carts", cart_items_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " log out", destroy_member_session_path, method: :delete, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
      <% elsif admin_signed_in? %>
      <!--管理者ログイン-->
        <li class="header_item">
          <%= link_to " items", admin_items_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " members", admin_members_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " orders", admin_orders_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " genres", admin_genres_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " log out", destroy_admin_session_path, method: :delete, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <form class="search">
        <input class="search-input"  type="text"  placeholder="Search">
        <%= button_tag( class: "btn btn-default btn-sm search-btn") do %>
        <%= content_tag :span, "", class: "glyphicon glyphicon-search" %>
        <% end %>
        </form>
      <% else %>
      <!--ログインしていない-->
        <li class="header_item">
          <%= link_to " about", homes_about_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " items", items_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " sign up", new_member_registration_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
        <li class="header_item">
          <%= link_to " log in", new_member_session_path, class: "header_btn glyphicon glyphicon-leaf" %>
        </li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <div class="row row-height">
        <%= yield %>
      </div>
    </div>
    <footter>
      <%= render 'layouts/footer' %>
    </footter>
  </body>
</html>