config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }

  namespace :admin do
    resources :members,except:[:new, :create, :destroy]
    resources :genres, except:[:new, :show, :destroy]
    resources :items, except:[:destroy]
    resources :orders, except:[:new, :create, :edit, :destroy]
    resources :ordered_items, only:[:update]
    root 'homes#top'
  end

  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations',
    passwords: 'members/passwords'
  }

  scope module: :public do
    root 'homes#top'
    get 'homes/about' => 'homes#about'
    resource :member, except:[:create, :new, :destroy] do
      collection do
        get 'leave'
        put 'actived'
        patch 'actived'
      end
    end

    resources :delivery_destinations, except:[:show, :new]
    resources :items, except:[:destroy]
    resources :cart_items, except:[:show, :new, :edit] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
    resources :orders, except:[:edit, :update, :destroy] do
      collection do
        post 'check'
        get 'thanks'
      end
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  has_many :delivery_destinations, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :last_name, presence: true, length: {maximum: 10, minimum: 1}, uniqueness: true
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, length: {maximum: 7, minimum: 7}
  validates :address, presence: true
  validates :phone_number, presence: true
  
  def registered?(delivery_destination)
    self.delivery_destinations.where(address: delivery_destination.address, postal_code: delivery_destination.postal_code, reciever_name: delivery_destination.reciever_name).exists? || delivery_destination.postal_code == self.postal_code && delivery_destination.address == self.address
  end
  
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
    redirect_to admin_members_path
    else
    render "edit"
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  private
  def member_params
  params.require(:member).permit(:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number, :is_deleted)
  end

end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :reject_member, only: [:create]

  protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
        flash[:error] = "このユーザーは退会済みです。"
        redirect_to new_member_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<div class="title">登録情報編集</div>

<%= form_with model:@member, local:true do |f| %>

<div class="field">
    <%= f.label '名前' %>
    <%= f.label '(姓) ' %>
    <%= f.text_field :first_name, autofocus: true %>
    <%= f.label '(名)' %>
    <%= f.text_field :last_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label 'フリガナ' %>
    <%= f.label '(セイ)' %>
    <%= f.text_field :first_name_kana, autofocus: true %>
    <%= f.label '(メイ)' %>
    <%= f.text_field :last_name_kana, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "メールアドレス" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label "郵便番号(ハイフンなし)" %>
    <%= f.text_field :postal_code, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所" %>
    <%= f.text_field :address, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "電話番号(ハイフンなし)" %>
    <%= f.text_field :phone_number, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "編集内容を保存する", class: "btn-sm btn-primary" %> <%= link_to "退会する", members_leave_path, class: "btn-sm btn-danger" %>
  </div>
<% end %>

app/views/members/leave.html.erb
<h3>本当に退会しますか？</h3>
<h4>退会すると、会員登録情報や<br>
これまでの購入履歴が閲覧できなくなります。<br>
退会する場合は、「退会する」をクリックしてください。</h4>

<h4><%= link_to "退会しない", edit_member_path, class: "btn-sm btn-primary" %> <%= link_to "退会する", members_actived_path, method: :put, class: "btn-sm btn-danger" %></h4>

app/views/members/show.html.erb
<div class="title">マイページ</div>

<h5>登録情報 <%= link_to "編集する", edit_member_path, class: "btn-sm btn-primary" %>  <%= link_to "パスワードを変更する", edit_member_password_path, class: "btn-sm btn-primary" %></h5>

<table border="1">
    <tr>
      <td>氏名</td>
      <td><%= @member.first_name %> <%= @member.last_name %></td>
    </tr>
    <tr>
      <td>カナ</td>
      <td><%= @member.first_name_kana %> <%= @member.last_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @member.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @member.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @member.phone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @member.email %></td>
    </tr>
  </table>

  <h5>配送先 <%= link_to "一覧を見る", delivery_destinations_path, class: "btn-sm btn-primary" %></h5>
  <h5>注文履歴 <%= link_to "一覧を見る", orders_path, class: "btn-sm btn-primary" %></h5>